"""add faturamento tables

Revision ID: efgh5678
Revises: d05b609a8955
Create Date: 2026-01-19 00:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efgh5678'
down_revision = 'd05b609a8955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('numero_fatura', sa.String(), nullable=False),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('valor_pago', sa.Float(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_fatura')
    )
    op.create_index(op.f('ix_faturas_id'), 'faturas', ['id'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.Column('valor_pago', sa.Float(), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('metodo_pagamento', sa.String(), nullable=False),
    sa.Column('referencia', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fatura_id'], ['faturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_id'), 'pagamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagamentos_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_faturas_id'), table_name='faturas')
    op.drop_table('faturas')
    # ### end Alembic commands ###